### Numpy
- Numpy stands for Numerical Python.
- Numpy is a python library used for working with arrays.

In [3]:
import numpy as np

In [4]:
np.__version__

'1.20.1'

In [5]:
# create 1D array
a1 = np.array([1,2,3,4,5])
print(a1)
print(a1.ndim)

[1 2 3 4 5]
1


In [6]:
# create 2D array
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# create 2D array
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [8]:
a3 = np.array([[[1,2],[3,4],[5,6]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[1 2]
  [3 4]
  [5 6]]]
3
(1, 3, 2)


In [9]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [10]:
a3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
(1, 4, 2)


In [11]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.itemsize)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
4


### Creating an array using range()
* np.array(range(start,end,step))
* np.array(range(start,end,step)).reshape(rows,columns)

In [12]:
a1 = np.array(range(10))
print(a1)
print(a1.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [13]:
a1 = np.array(range(10)).reshape(1,5,2)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
3
(1, 5, 2)


In [14]:
a1 = np.array(range(10)).reshape(2,5,1)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]
3
(2, 5, 1)


In [15]:
a1 = np.array(range(10,40)).reshape(1,5,6)
print(a1)
print(a1.ndim)
print(a1.shape)

[[[10 11 12 13 14 15]
  [16 17 18 19 20 21]
  [22 23 24 25 26 27]
  [28 29 30 31 32 33]
  [34 35 36 37 38 39]]]
3
(1, 5, 6)


In [16]:
a2 = np.arange(10,40).reshape(5,6)
print(a2)
print(a2.ndim)
print(a2.size)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
2
30


In [17]:
a2 = np.arange(1,40,2).reshape(5,4)
print(a2)
print(a2.ndim)
print(a2.size)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
2
20


In [18]:
# zeros matrix
z = np.zeros((5,5))
print(z)
print

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<function print>

In [19]:
# zeros matrix
z = np.zeros((5,5))
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
0.0
<class 'numpy.float64'>


In [20]:
z = np.zeros((5,5),dtype="int")
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
<class 'numpy.int32'>


In [21]:
# ones matrix
one = np.ones((5,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
one = np.ones((5,4),dtype=int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
one = np.ones((5,4),dtype=int)
print(one*5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [25]:
r = np.random.randint(10)
r

8

In [26]:
r = np.random.randint(10,20)
r

19

In [27]:
r = np.random.randint(10,20,5)
r

array([15, 18, 15, 11, 18])

In [28]:
r = np.random.randint(10,20,5)
print(r)

[19 11 18 12 19]


In [29]:
r = np.random.randint(10,40,20).reshape(5,4)
print(r)

[[34 16 14 36]
 [39 18 30 13]
 [18 12 33 28]
 [29 12 15 16]
 [16 27 20 29]]


In [30]:
r = np.random.randint(10,40,(6,5))
print(r)

[[17 16 28 21 36]
 [28 35 15 17 24]
 [18 22 17 25 27]
 [35 24 30 20 31]
 [32 35 34 25 32]
 [12 24 39 24 12]]


In [31]:
np.random.random()

0.21403872839314042

In [32]:
np.random.random((2,3))

array([[0.55573506, 0.94641673, 0.07843395],
       [0.52248822, 0.14375771, 0.47006076]])

In [33]:
a1

array([[[10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]]])

In [44]:
print(np.mean(a1))

24.5


In [34]:
print(np.median(a1))

24.5


In [35]:
print(np.log(1))

0.0
